name: facial_recognition_app
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.9
  - streamlit=1.5.0
  - pillow=9.4.0
  - qrcode=7.3.1
  - opencv=4.5.5
  - numpy=1.21.5
  - pandas=1.4.1
  - requests=2.27.1
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.6
  - google-auth-httplib2=0.15.0
  - google-api-python-client=2.32.0
  - pip
  - pip:
    - qrcode[pil]>=7.3.1
    - face_recognition==1.3.0
    - dlib>=19.7.0
    - CMake==3.19.5
  
