name: facial_recognition_app
channels:
  - conda-forge
dependencies:
  - streamlit
  - dlib
  - opencv
  - numpy
  - pandas
  - requests
  - google-auth
  - google-auth-oauthlib
  - google-auth-httplib2
  - google-api-python-client
  - Pillow
  - CMake
  - base64
  - BytesIO
  - json
