name: facial_recognition_app
channels:
  - conda-forge
dependencies:
  - python=3.8
  - streamlit=1.5.0
  - dlib=19.22.1
  - pillow=9.4.0
  - firebase-admin=5.3.0
  - qrcode=7.3.1
  - opencv=4.5.5
  - numpy=1.22.3
  - pandas=1.4.1
  - requests=2.27.1
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.6
  - google-auth-httplib2=0.1.4
  - google-api-python-client=2.37.0
  - pip:
    - qrcode[pil]>=7.3.1
    - face_recognition==1.3.0
    - CMake==3.19.5
    - json
  - pip
